// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCardToDeckByName(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddCardToDeckByName'](arg1, arg2, arg3);
}

export function BuildDeckFromCompare(arg1) {
  return window['go']['app']['App']['BuildDeckFromCompare'](arg1);
}

export function CommitImport(arg1) {
  return window['go']['app']['App']['CommitImport'](arg1);
}

export function CompareDeck(arg1) {
  return window['go']['app']['App']['CompareDeck'](arg1);
}

export function DeleteDeck(arg1) {
  return window['go']['app']['App']['DeleteDeck'](arg1);
}

export function LendCard(arg1) {
  return window['go']['app']['App']['LendCard'](arg1);
}

export function ListCollection() {
  return window['go']['app']['App']['ListCollection']();
}

export function ListDeckCards(arg1) {
  return window['go']['app']['App']['ListDeckCards'](arg1);
}

export function ListDecks() {
  return window['go']['app']['App']['ListDecks']();
}

export function ListLentCards(arg1) {
  return window['go']['app']['App']['ListLentCards'](arg1);
}

export function PreviewCSVImport(arg1) {
  return window['go']['app']['App']['PreviewCSVImport'](arg1);
}

export function PreviewTextImport(arg1) {
  return window['go']['app']['App']['PreviewTextImport'](arg1);
}

export function RenameDeck(arg1, arg2) {
  return window['go']['app']['App']['RenameDeck'](arg1, arg2);
}

export function RepairCompareMismatches(arg1) {
  return window['go']['app']['App']['RepairCompareMismatches'](arg1);
}

export function ResolverStatus() {
  return window['go']['app']['App']['ResolverStatus']();
}

export function ReturnCard(arg1, arg2) {
  return window['go']['app']['App']['ReturnCard'](arg1, arg2);
}

export function SetDeckCardQuantity(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetDeckCardQuantity'](arg1, arg2, arg3, arg4);
}
