// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {analysis} from '../models';
import {collection} from '../models';
import {storage} from '../models';
import {cards} from '../models';

export function AddCardToDeckByName(arg1:number,arg2:string,arg3:number):Promise<void>;

export function AnalyzeDeckDraw(arg1:analysis.DeckDrawAnalysisRequest):Promise<analysis.DeckDrawAnalysisResult>;

export function BuildDeckFromCompare(arg1:collection.BuildDeckInput):Promise<number>;

export function CommitImport(arg1:Array<collection.ResolvedLine>):Promise<void>;

export function CompareDeck(arg1:string):Promise<collection.DeckCompareResult>;

export function CreateCollectionFolder(arg1:any,arg2:string):Promise<number>;

export function CreateCollectionTag(arg1:string,arg2:string):Promise<number>;

export function DeleteCollectionFolder(arg1:number):Promise<void>;

export function DeleteCollectionTag(arg1:number):Promise<void>;

export function DeleteDeck(arg1:number):Promise<void>;

export function EndDeckSimulation(arg1:string):Promise<void>;

export function FormatMissingDecklist(arg1:Array<collection.DeckCompareRow>):Promise<string>;

export function Hypergeometric(arg1:analysis.HypergeometricRequest):Promise<analysis.HypergeometricResult>;

export function LendCard(arg1:storage.LendInput):Promise<void>;

export function ListCollection():Promise<Array<cards.CollectionItem>>;

export function ListCollectionFolders():Promise<Array<cards.CollectionFolder>>;

export function ListCollectionInFolder(arg1:number):Promise<Array<cards.FolderCard>>;

export function ListCollectionTags():Promise<Array<cards.CollectionTag>>;

export function ListDeckCards(arg1:number):Promise<Array<cards.DeckCard>>;

export function ListDecks():Promise<Array<cards.Deck>>;

export function ListFormatTargets():Promise<Array<analysis.FormatTarget>>;

export function ListLentCards(arg1:boolean):Promise<Array<cards.LentCard>>;

export function MoveCollectionCopies(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function MoveCollectionFolder(arg1:number,arg2:any):Promise<void>;

export function PreviewCSVImport(arg1:Array<number>):Promise<collection.ImportPreview>;

export function PreviewTextImport(arg1:string):Promise<collection.ImportPreview>;

export function RenameCollectionFolder(arg1:number,arg2:string):Promise<void>;

export function RenameCollectionTag(arg1:number,arg2:string):Promise<void>;

export function RenameDeck(arg1:number,arg2:string):Promise<void>;

export function RepairCompareMismatches(arg1:Array<collection.RepairCandidate>):Promise<void>;

export function ResolverStatus():Promise<string>;

export function ReturnCard(arg1:number,arg2:string):Promise<void>;

export function SetCardTags(arg1:string,arg2:Array<number>):Promise<void>;

export function SetDeckCardQuantity(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SimDrawCard(arg1:string):Promise<analysis.SimulationState>;

export function SimMulligan(arg1:string):Promise<analysis.SimulationState>;

export function SimNewOpening(arg1:string):Promise<analysis.SimulationState>;

export function SimPutOnBottom(arg1:string,arg2:string):Promise<analysis.SimulationState>;

export function SimSetOracleFocus(arg1:string,arg2:string):Promise<analysis.SimulationState>;

export function StartDeckSimulation(arg1:number,arg2:string,arg3:string,arg4:number):Promise<analysis.SimulationState>;

export function UpdateCollectionTagColor(arg1:number,arg2:string):Promise<void>;
